pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo '✅ Code récupéré depuis GitHub'
            }
        }

        stage('Build Frontend') {
            steps {
                dir('Stage-PFE-AICTO/frontend') {
                    sh '''
                        npm install
                        chmod -R 755 node_modules/.bin/
                        npm run build
                    '''
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('Stage-PFE-AICTO/backend') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Tests Frontend') {
            steps {
                dir('Stage-PFE-AICTO/frontend') {
                    sh 'npm test -- --watch=false --no-progress'
                }
            }
        }

        stage('Tests Backend') {
            steps {
                dir('Stage-PFE-AICTO/backend') {
                    sh 'pytest tests/ --maxfail=1 -v'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo '🚀 Déploiement terminé avec succès !'
            }
        }
    }

    post {
        success {
            echo '✅ Build réussi !'
        }
        failure {
            echo '❌ Build échoué - Vérifiez les logs'
        }
    }
}